# Generated by Django 3.0.2 on 2020-02-25 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('liking_users', models.ManyToManyField(related_name='liked_messages', to='a_app.User')),
                ('message_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_messages', to='a_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_comments', to='a_app.User')),
                ('liking_users', models.ManyToManyField(related_name='liked_comments', to='a_app.User')),
                ('parent_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_comments', to='a_app.Message')),
            ],
        ),
    ]
